name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pr-build:
    runs-on: ubuntu-latest
#    container:
#      image: sbtscala/scala-sbt:eclipse-temurin-21.0.6_7_1.10.11_3.6.4
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install asdf & tools
      uses: asdf-vm/actions/install@v4
    - name: Set up sbt
      uses: coursier/setup-action@v1
      with:
        apps: sbt
    - name: Build and Test
      run: sbt -v +test
